// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtDfZKhBfWZjnnHkvD5jRW0Ju8ypaRtbY',
    appId: '1:671804537123:web:57b2d827163e6c9499b496',
    messagingSenderId: '671804537123',
    projectId: 'instagramer-6599e',
    authDomain: 'instagramer-6599e.firebaseapp.com',
    storageBucket: 'instagramer-6599e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrmeIb-M0S654WVL5aFkoYk54eFgSd9Oc',
    appId: '1:671804537123:android:b01b385962ea0ee399b496',
    messagingSenderId: '671804537123',
    projectId: 'instagramer-6599e',
    storageBucket: 'instagramer-6599e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmIosAV9XKyp7tuYhx0n3la8x-0iLphSo',
    appId: '1:671804537123:ios:b9e62516f884f61699b496',
    messagingSenderId: '671804537123',
    projectId: 'instagramer-6599e',
    storageBucket: 'instagramer-6599e.appspot.com',
    iosBundleId: 'com.example.instagramer',
  );

}